server.port=8080

spring.datasource.url=jdbc:postgresql://stg-db-server:5432/gym_crm_stg
spring.datasource.username=stg_user
spring.datasource.password=stg_secure_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=INFO