server.port=80

spring.datasource.url=jdbc:postgresql://prod-db-server:5432/gym_crm_prod
spring.datasource.username=prod_admin
spring.datasource.password=${DB_PASSWORD_ADMIN}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

logging.level.root=WARN
logging.level.gym.crm=ERROR

management.endpoints.web.exposure.include=health,prometheus