spring.data.mongodb.repositories.enabled=true

spring.data.mongodb.uri=mongodb://127.0.0.1:27017/unused_db

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.activemq.broker-url=vm://localhost?broker.persistent=false

spring.main.lazy-initialization=true