spring.application.name=trainer-workload-service
server.port=8081

spring.data.mongodb.uri=mongodb://mongodb:27017/trainer_workload_db

spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin

app.queue.name=trainer-workload-queue

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.data.mongodb.repositories.enabled=true
spring.main.lazy-initialization=false